# Form implementation generated from reading ui file 'giaodien.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: #FF0000")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(210, 340, 401, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label2.setFont(font)
        self.label2.setStyleSheet(" text-align: center;\n"
"")
        self.label2.setObjectName("label2")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 60, 711, 71))
        font = QtGui.QFont()
        font.setPointSize(31)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font-weight: bold;\n"
" text-align: center;")
        self.label_2.setObjectName("label_2")
        self.number = QtWidgets.QLabel(parent=self.centralwidget)
        self.number.setGeometry(QtCore.QRect(230, 170, 141, 141))
        self.number.setStyleSheet(" background-color: #FFFFFF;\n"
"    border: 8px solid #FFD700;\n"
"    border-radius: 20px;\n"
"    text-align: center;\n"
"    font-size: 25pt;\n"
"    font-weight: bold; \n"
"      color: #3B82F6;")
        self.number.setText("")
        self.number.setObjectName("number")
        self.push = QtWidgets.QPushButton(parent=self.centralwidget)
        self.push.setGeometry(QtCore.QRect(240, 390, 281, 51))
        self.push.setStyleSheet("\n"
"    background-color: #FFD700; \n"
"    color: white; \n"
"    font-size: 16pt;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px 20px; \n"
"    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); \n"
" text-align: center;")
        self.push.setObjectName("push")
        self.kq = QtWidgets.QLabel(parent=self.centralwidget)
        self.kq.setGeometry(QtCore.QRect(270, 190, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(90)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.kq.setFont(font)
        self.kq.setStyleSheet("font: 90pt \"Segoe UI\"; \n"
"font-weight: bold; \n"
"text-align: center; \n"
"color: #007BFF; \n"
"border: none;\n"
"background-color: transparent;\n"
"vertical-align: middle")
        self.kq.setText("")
        self.kq.setObjectName("kq")
        self.kq_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.kq_2.setGeometry(QtCore.QRect(470, 190, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(90)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.kq_2.setFont(font)
        self.kq_2.setStyleSheet("font: 90pt \"Segoe UI\"; \n"
"font-weight: bold; \n"
"text-align: center; \n"
"color: #007BFF; \n"
"border: none;\n"
"background-color: transparent;\n"
"vertical-align: middle")
        self.kq_2.setText("")
        self.kq_2.setObjectName("kq_2")
        self.number_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.number_2.setGeometry(QtCore.QRect(430, 170, 141, 141))
        self.number_2.setStyleSheet(" background-color: #FFFFFF;\n"
"    border: 8px solid #FFD700;\n"
"    border-radius: 20px;\n"
"    text-align: center;\n"
"    font-size: 25pt;\n"
"    font-weight: bold; \n"
"    color: #3B82F6;")
        self.number_2.setText("")
        self.number_2.setObjectName("number_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        self.menuTungxucxac = QtWidgets.QMenu(parent=self.menubar)
        self.menuTungxucxac.setObjectName("menuTungxucxac")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuTungxucxac.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label2.setText(_translate("MainWindow", "Nhấn vào nút để tung xúc xắc"))
        self.label_2.setText(_translate("MainWindow", "TRÒ CHƠI TUNG XÚC XẮC"))
        self.push.setText(_translate("MainWindow", "TUNG XÚC XẮC"))
        self.menuTungxucxac.setTitle(_translate("MainWindow", "Tungxucxac"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
