# Form implementation generated from reading ui file 'C:\Users\jimmy\PycharmProjects\ProjectNhom\giaodien.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(210, 340, 401, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label2.setFont(font)
        self.label2.setStyleSheet(" text-align: center;\n"
                                  "")
        self.label2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label2.setObjectName("label2")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 60, 711, 71))
        font = QtGui.QFont()
        font.setPointSize(31)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font-weight: bold;\n"
                                   " text-align: center;")
        self.label_2.setObjectName("label_2")
        self.number = QtWidgets.QLabel(parent=self.centralwidget)
        self.number.setGeometry(QtCore.QRect(230, 170, 141, 141))
        self.number.setStyleSheet(" background-color: #FFFFFF;\n"
                                  "    border: 8px solid #3B82F6;\n"
                                  "    border-radius: 20px;\n"
                                  "    text-align: center;\n"
                                  "    font-size: 25pt;\n"
                                  "    font-weight: bold; \n"
                                  "    color: #3B82F6;")
        self.number.setText("")
        self.number.setObjectName("number")
        self.push = QtWidgets.QPushButton(parent=self.centralwidget)
        self.push.setGeometry(QtCore.QRect(260, 390, 281, 51))
        self.push.setStyleSheet("\n"
                                "    background-color: #4F46E5; \n"
                                "    color: white; \n"
                                "    font-size: 16pt;\n"
                                "    font-weight: bold;\n"
                                "    border: none;\n"
                                "    border-radius: 10px;\n"
                                "    padding: 10px 20px; \n"
                                "    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); \n"
                                " text-align: center;")
        self.push.setObjectName("push")
        self.kqtungxucxac = QtWidgets.QLabel(parent=self.centralwidget)
        self.kqtungxucxac.setGeometry(QtCore.QRect(270, 190, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(90)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.kqtungxucxac.setFont(font)
        self.kqtungxucxac.setStyleSheet("font: 90pt \"Segoe UI\"; \n"
                              "font-weight: bold; \n"
                              "text-align: center; \n"
                              "color: #007BFF; \n"
                              "border: none;\n"
                              "background-color: transparent;\n"
                              "vertical-align: middle")
        self.kqtungxucxac.setText("")
        self.kqtungxucxac.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.kqtungxucxac.setObjectName("kqtungxucxac")
        self.kqtungxucxac_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.kqtungxucxac_2.setGeometry(QtCore.QRect(470, 190, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(90)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.kqtungxucxac_2.setFont(font)
        self.kqtungxucxac_2.setStyleSheet("font: 90pt \"Segoe UI\"; \n"
                                "font-weight: bold; \n"
                                "text-align: center; \n"
                                "color: #007BFF; \n"
                                "border: none;\n"
                                "background-color: transparent;\n"
                                "vertical-align: middle")
        self.kqtungxucxac_2.setText("")
        self.kqtungxucxac_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.kqtungxucxac_2.setObjectName("kqtungxucxac_2")
        self.number_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.number_2.setGeometry(QtCore.QRect(430, 170, 141, 141))
        self.number_2.setStyleSheet(" background-color: #FFFFFF;\n"
                                    "    border: 8px solid #3B82F6;\n"
                                    "    border-radius: 20px;\n"
                                    "    text-align: center;\n"
                                    "    font-size: 25pt;\n"
                                    "    font-weight: bold; \n"
                                    "    color: #3B82F6;")
        self.number_2.setText("")
        self.number_2.setObjectName("number_2")

        # === WIDGET CÁ CƯỢC MỚI ===
        self.label_sodu_text = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_sodu_text.setGeometry(QtCore.QRect(260, 460, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        self.label_sodu_text.setFont(font)
        self.label_sodu_text.setObjectName("label_sodu_text")

        self.label_sodu_value = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_sodu_value.setGeometry(QtCore.QRect(370, 460, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        self.label_sodu_value.setFont(font)
        self.label_sodu_value.setStyleSheet("color: #16A34A;")
        self.label_sodu_value.setObjectName("label_sodu_value")

        self.label_bet_text = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_bet_text.setGeometry(QtCore.QRect(260, 500, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        self.label_bet_text.setFont(font)
        self.label_bet_text.setObjectName("label_bet_text")

        self.spinBox_bet = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.spinBox_bet.setGeometry(QtCore.QRect(370, 500, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.spinBox_bet.setFont(font)
        self.spinBox_bet.setObjectName("spinBox_bet")

        self.label_message = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_message.setGeometry(QtCore.QRect(100, 540, 600, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        self.label_message.setFont(font)
        self.label_message.setStyleSheet("color: #DC2626;")
        self.label_message.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_message.setObjectName("label_message")

        # Nâng các label kết quả lên
        self.number.raise_()
        self.number_2.raise_()
        self.kqtungxucxac.raise_()
        self.kqtungxucxac_2.raise_()

        # ==========================

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuTungxucxac = QtWidgets.QMenu(parent=self.menubar)
        self.menuTungxucxac.setObjectName("menuTungxucxac")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuTungxucxac.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tung_xuc_xac"))
        self.label2.setText(_translate("MainWindow", "Đặt cược và nhấn nút! Thắng nếu ra số đôi."))
        self.label_2.setText(_translate("MainWindow", "TRÒ CHƠI TUNG XÚC XẮC"))
        self.push.setText(_translate("MainWindow", "CƯỢC VÀ TUNG"))
        self.menuTungxucxac.setTitle(_translate("MainWindow", "Tungxucxac"))

        # === Thêm text cho widget mới ===
        self.label_sodu_text.setText(_translate("MainWindow", "Số dư:"))
        self.label_sodu_value.setText(_translate("MainWindow", "1,000 $"))
        self.label_bet_text.setText(_translate("MainWindow", "Tiền cược:"))
        self.label_message.setText(_translate("MainWindow", "Chúc bạn may mắn!"))
        # ===============================
